config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
               registrations: 'users/registrations' }
  root 'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'

  resources :users, only: %w(index show destroy) do
    member do
      get :following, :followers
    end
  end

  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t('footer.the') %> <a href="http://www.railstutorial.org"><%= t('tutorial') %></a>
    <%=t('footer.by') %> <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('about_page'), about_path %></li>
      <li><%= link_to t('contact_page'), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t('footer.news') %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t('logo'), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('header.home'), root_path %></li>
        <li><%= link_to t('help_page'), help_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to t('header.users'), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('header.account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('profile'), current_user %></li>
              <li><%= link_to t('header.setting'), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('header.logout'), destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('login'), user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>